/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGfwrQueriesRouteImport } from './routes/api/gfwr/queries'
import { Route as ApiGfwTrackRouteImport } from './routes/api/gfw/track'
import { Route as ApiGfwEventsRouteImport } from './routes/api/gfw/events'
import { Route as ApiGfwVesselsSearchRouteImport } from './routes/api/gfw/vessels/search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGfwrQueriesRoute = ApiGfwrQueriesRouteImport.update({
  id: '/api/gfwr/queries',
  path: '/api/gfwr/queries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGfwTrackRoute = ApiGfwTrackRouteImport.update({
  id: '/api/gfw/track',
  path: '/api/gfw/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGfwEventsRoute = ApiGfwEventsRouteImport.update({
  id: '/api/gfw/events',
  path: '/api/gfw/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGfwVesselsSearchRoute = ApiGfwVesselsSearchRouteImport.update({
  id: '/api/gfw/vessels/search',
  path: '/api/gfw/vessels/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/gfw/events': typeof ApiGfwEventsRoute
  '/api/gfw/track': typeof ApiGfwTrackRoute
  '/api/gfwr/queries': typeof ApiGfwrQueriesRoute
  '/api/gfw/vessels/search': typeof ApiGfwVesselsSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/gfw/events': typeof ApiGfwEventsRoute
  '/api/gfw/track': typeof ApiGfwTrackRoute
  '/api/gfwr/queries': typeof ApiGfwrQueriesRoute
  '/api/gfw/vessels/search': typeof ApiGfwVesselsSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/gfw/events': typeof ApiGfwEventsRoute
  '/api/gfw/track': typeof ApiGfwTrackRoute
  '/api/gfwr/queries': typeof ApiGfwrQueriesRoute
  '/api/gfw/vessels/search': typeof ApiGfwVesselsSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/gfw/events'
    | '/api/gfw/track'
    | '/api/gfwr/queries'
    | '/api/gfw/vessels/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/gfw/events'
    | '/api/gfw/track'
    | '/api/gfwr/queries'
    | '/api/gfw/vessels/search'
  id:
    | '__root__'
    | '/'
    | '/api/gfw/events'
    | '/api/gfw/track'
    | '/api/gfwr/queries'
    | '/api/gfw/vessels/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiGfwEventsRoute: typeof ApiGfwEventsRoute
  ApiGfwTrackRoute: typeof ApiGfwTrackRoute
  ApiGfwrQueriesRoute: typeof ApiGfwrQueriesRoute
  ApiGfwVesselsSearchRoute: typeof ApiGfwVesselsSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gfwr/queries': {
      id: '/api/gfwr/queries'
      path: '/api/gfwr/queries'
      fullPath: '/api/gfwr/queries'
      preLoaderRoute: typeof ApiGfwrQueriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gfw/track': {
      id: '/api/gfw/track'
      path: '/api/gfw/track'
      fullPath: '/api/gfw/track'
      preLoaderRoute: typeof ApiGfwTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gfw/events': {
      id: '/api/gfw/events'
      path: '/api/gfw/events'
      fullPath: '/api/gfw/events'
      preLoaderRoute: typeof ApiGfwEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gfw/vessels/search': {
      id: '/api/gfw/vessels/search'
      path: '/api/gfw/vessels/search'
      fullPath: '/api/gfw/vessels/search'
      preLoaderRoute: typeof ApiGfwVesselsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiGfwEventsRoute: ApiGfwEventsRoute,
  ApiGfwTrackRoute: ApiGfwTrackRoute,
  ApiGfwrQueriesRoute: ApiGfwrQueriesRoute,
  ApiGfwVesselsSearchRoute: ApiGfwVesselsSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
